[package]
name = "shell-toy"
version = "0.1.0"
edition = "2021"
description = "A \"cowsay | fortune\" implementation in Rust, i.e. a nice little toy to liven up your shell."
license = "MIT"
repository = "https://github.com/FaceFTW/shell-toy"

[[bin]]
name = "sh-toy"
path = "src/main.rs"

[dependencies]
owo-colors = "3"
nom = "7"
tinyrand = "0.5"
getrandom = "0.2"
argh = "0.1"
textwrap = "0.16"
strip-ansi-escapes = "0.2"
unicode-width = "0.1"

[features]

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 'z'
strip = true
panic = "abort"
