[package]
name = "shell-intro"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sh-intro"
path = "src/main.rs"

[dependencies]
anstyle = "1"
owo-colors = "3"
anstyle-owo-colors = "2"
nom = "7"
rand = "0.8.5"
byteorder = "1"
argh = "0.1"
# clap = { version = "4.5.4", features = ["derive"] }
textwrap = "*"
strip-ansi-escapes = "*"
unicode-width = "*"

[features]
